name: Tests

# Test Tagulous on:
#   all supported Django and Python versions
#   against sqlite, postgresql and mysql

on:
  push:
  pull_request:

jobs:
  test-sqlite:
    name: py-${{ matrix.python }} dj-${{ matrix.django }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Test Python versions - Django LTS on supported Python - dj3.2, py3.6-3.9
          - python: "3.6"
            django: "3.2"
          - python: "3.7"
            django: "3.2"
          - python: "3.8"
            django: "3.2"
          - python: "3.9"
            django: "3.2"
          # Test Django versions - Django supported on Python latest - dj2.2-3.3, py3.9
          - python: "3.9"
            django: "2.2"
          - python: "3.9"
            django: "3.0"
          - python: "3.9"
            django: "3.1"
          - python: "3.9"
            django: "3.2"
          - python: "3.9"
            django: "4.0"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt
          pip install "django~=${{ matrix.django }}.0"
      - name: Test
        run: |
          pytest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: ${{ matrix.python }}-${{ matrix.django }}

  test-postgres:
    name: py-${{ matrix.python }} dj-${{ matrix.django }} PostgreSQL
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Django LTS on Python latest - dj2.2, py3.9
          - python: "3.9"
            django: "2.2"
          # Django latest on Python latest - dj3.2, py3.9
          - python: "3.9"
            django: "4.0"

    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt
          pip install psycopg2
          pip install "django~=${{ matrix.django }}.0"
      - name: Test
        run: |
          pytest
        env:
          DATABASE_ENGINE: postgresql
          DATABASE_HOST: localhost
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: ${{ matrix.python }}-${{ matrix.django }}-postgres

  test-mysql:
    name: py-${{ matrix.python }} dj-${{ matrix.django }} MySQL
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Django LTS on Python latest - dj2.2, py3.9
          - python: "3.9"
            django: "2.2"
          # Django latest on Python latest - dj3.2, py3.9
          - python: "3.9"
            django: "4.0"

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt
          pip install mysqlclient
          pip install "django~=${{ matrix.django }}.0"
      - name: Test
        run: |
          pytest
        env:
          DATABASE_ENGINE: mysql
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 3306
          DATABASE_USER: root
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: ${{ matrix.python }}-${{ matrix.django }}-mysql
